apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: jans-table-api
spec:
  image: griga/jans-table-api
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink//usrlib/jans-table-api-jar-with-dependencies.jar
    parallelism: 1
    upgradeMode: stateless
